apiVersion: v1
clusters:
- name: tattycluster
  cluster:
    certificate-authority: ca-hou02-tattycluster.pem
    server: https://c6.hou02.containers.cloud.ibm.com:23036
contexts:
- name: tattycluster
  context:
    cluster: tattycluster
    user: tatiana.douglas@ibm.com
    namespace: default
current-context: tattycluster
kind: Config
users:
- name: tatiana.douglas@ibm.com
  user:
    auth-provider:
      name: oidc
      config:
        client-id: kube
        client-secret: kube
        id-token: eyJraWQiOiIyMDE5MDIwNCIsImFsZyI6IlJTMjU2In0.eyJpYW1faWQiOiJJQk1pZC01NTAwMDBRQUNCIiwiaXNzIjoiaHR0cHM6Ly9pYW0uYmx1ZW1peC5uZXQvaWRlbnRpdHkiLCJzdWIiOiJUYXRpYW5hLkRvdWdsYXNAaWJtLmNvbSIsImF1ZCI6Imt1YmUiLCJnaXZlbl9uYW1lIjoiVGF0aWFuYSIsImZhbWlseV9uYW1lIjoiRG91Z2xhcyIsIm5hbWUiOiJUYXRpYW5hIERvdWdsYXMiLCJlbWFpbCI6IlRhdGlhbmEuRG91Z2xhc0BpYm0uY29tIiwiZXhwIjoxNTU5MjM2MDMwLCJzY29wZSI6ImlibSBvcGVuaWQgY29udGFpbmVycy1rdWJlcm5ldGVzIiwiaWF0IjoxNTU5MjMyNDMwLCJzdWJfMTg1OTBmZTg1NGM1NGU0Njg3M2QzYmNkN2M2YTMzMTQiOiJ0YXRpYW5hLmRvdWdsYXNAaWJtLmNvbSIsImdyb3Vwc18xODU5MGZlODU0YzU0ZTQ2ODczZDNiY2Q3YzZhMzMxNCI6W119.WHjLqvRCxGtcOoSS3mR1ACSb_24iI6uksuqbNTwRCFGu7TdBVa4RrB94xMEVarMLSYqUstsGUPAUeODz0WvUwJy-W3C3KOqwk_6MU4XZGrCyn4Ve3OOx9u-NIJQ5o_AtqoLR86glor4XJdrqG7nryyrL4oTqW6KMWGHgWCkcCrgHgFhta1OOqxC2E3-YkEKjVIRI410gmBNYcjKLmVz-FvuYyX_r1Jwx3lnpJnhnHyPcTTtlRTvqN7CQCeYJZs06frkYlluvL_iu3NhhIFejXxhiQJTwhmPRZF2zT7DzxabvxAFplWl6IhomJUvV4VpHiDSwphNsknUGTdxaaMB7zw
        idp-issuer-url: https://iam.bluemix.net/identity
        refresh-token: ReU0IH_wQ9phwGgPFYL6J_5Eb8jf5MhlvxUulSLbIM-FqMcOSdj4ATBDEaJNK4Jidgypk3ZEDWi_W2pWpVRy9a6e01Miy5zi-GfGnT8HkVb8MsSwxqzGCDgTVuhrrQkPXumNC0mcUd6hG0oqS8TuXKLO0szLh_TVpF64yqJH6UoZTmFuxSi22Np_QXpf2464Rdys9WZ2T8HoHSl601RQ-399UXoBPjK4q5qxU98WibNHk7cmpdbbiA2SESWLcKhi5uw0T6rBbzbRjxF8OdckMN40O_2RalCNW7bXjPFr-6hsu53GNsaD6FQMcqyzrSRhX4UZ0IGlMhu3hoPqEa8Ccv2sVrSRCIDlixUK7BAYeZRYlAfK43TaAi5dcGUuWaJp-RyGgJFGpQ2z7UD3GTMx02M66dqXT5fwOEX13zuX4idBkc2jHmaGntgC16vPuU8KH7_WEr33o1OK_qRas1mLheNBqMqEfYXYcWWF7p4VYYORlVEArStGfY0giNCIp0eRtn6gnjgeqbIVCelLJxCRv3Yn22g7ww2Aeon3gM2UlOVCIcLGLKx9oH2jLgIAdGV06hrYBxfARzm7HGHfKg-bnuwmratmpRhx70RFBp-HXqHaKzZxAfXxBTfBCm3LwZzasOvSy3gorMjHuvRReOkmAAxcFyGGRv7-EqjXud_9F444aRfkXtv8J45rnCyCGuc0QleFJ-OS0zR4jiY0zvI7OFoRPHIMDjNH7Y6raHwGe1eBohHy1Rj0m1VGU4oKqIO69qr0jwc-nsYxVbmtZ6RwJD9HxfLI9ZvEMEpUnixAiYd-NmdQEPHFvYtTqkq-5WADR4VZimUqeek0rywspqMqxAvSZlDObGvd93qfaKQyIbx-_qdfNjH8GiSQN_pzrgDnGv6NbsLyhijgVWRyxMztxTTdwPiO5mhx2DREF69Q-c7WIfPk21gypJ1RMgPwhg84fO9yBga8i0dojv3RGEyybxP8SyyFNm7g3GQlhkJmwOEwHvweAzvwMidJMOMnv_f10j8
