version: 2.1

setup-environment: &setup-environment
  machine:
    image: ubuntu-1604:201903-01

jobs:
  verify-build:
    <<: *setup-environment
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install curl sshpass -y
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - run: sudo mv ./kubectl /usr/local/bin/kubectl
      - run: sshpass -p "Cobalt235!" scp -r root@138.197.227.8:/opt/* /home/circleci
      - run: docker build -t btl5037/sampleapp .
      - run: docker login -u btl5037 -p Cobalt235!
      - run: docker push btl5037/sampleapp
      - run: 
          name: Create Deployment
          command: kubectl create -f deploy.yml
          environment:
            KUBECONFIG: /home/circleci/kube-config-hou02-tattycluster.yml
            KUBERNETES_MASTER: https://c6.hou02.containers.cloud.ibm.com:23036/
      - run: 
          name: Create Service
          command: kubectl create -f service.yml
          environment:
            KUBECONFIG: /home/circleci/kube-config-hou02-tattycluster.yml
            KUBERNETES_MASTER: https://c6.hou02.containers.cloud.ibm.com:23036/
      - run:
          name: Check State
          command: >
            state=`kubectl describe pod -n kube-system kube-apiserver-docker-for-desktop | grep Ready | tail -n 1`
            if [[ $state ~= "True" ]]; then
              exit 0
            else;
              state=`kubectl describe pod -n kube-system kube-apiserver-docker-for-desktop | grep Ready | tail -n 1`
            fi;
          environment:
            KUBECONFIG: /home/circleci/kube-config-hou02-tattycluster.yml
            KUBERNETES_MASTER: https://c6.hou02.containers.cloud.ibm.com:23036/
      - run: >
          result=`curl 173.193.75.135:30000`
          echo $result
      
workflows:
  fabric:
    jobs:
      - verify-build
      
